projects:
  mypwa2023:
    schemaPath: src/graphql/schema.json
    includes:
      - mypwa.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
